# Generated by Django 4.1.1 on 2022-09-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_code', models.CharField(blank=True, help_text='상품 관리용 코드', max_length=10, null=True)),
                ('name', models.CharField(help_text='상품 이름', max_length=128)),
                ('standard_price', models.IntegerField(default=0, help_text='정가')),
                ('original_sell_price', models.IntegerField(default=0, help_text='기준 판매가')),
                ('sell_price', models.IntegerField(default=0, help_text='현재 판매가')),
                ('original_cost', models.IntegerField(default=0, help_text='기존 제조 원가/ 공급가액')),
                ('pro_seil_prace', models.CharField(blank=True, default=0, help_text='세일 가격', max_length=10, null=True)),
                ('pro_seil_percent', models.CharField(blank=True, default=0, help_text='세일 %', max_length=10, null=True)),
            ],
        ),
    ]
