# Generated by Django 4.1.1 on 2022-09-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(blank=True, help_text='user_email', max_length=254, null=True),
        ),
    ]
