# Generated by Django 4.1.1 on 2022-09-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_sell_price',
            field=models.IntegerField(default='', help_text='기준 판매가'),
        ),
    ]
