# Generated by Django 4.1.1 on 2022-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_original_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_cost',
            field=models.IntegerField(blank=True, default=0, help_text='기존 제조 원가/ 공급가액', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_sell_price',
            field=models.IntegerField(blank=True, default='', help_text='기준 판매가', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.IntegerField(blank=True, default=0, help_text='현재 판매가', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_price',
            field=models.IntegerField(blank=True, default=0, help_text='정가', null=True),
        ),
    ]
