# Generated by Django 4.1.1 on 2022-09-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_original_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_sell_price',
            field=models.IntegerField(blank=True, default=0, help_text='기준 판매가', null=True),
        ),
    ]
