# Generated by Django 4.0.6 on 2022-09-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_original_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='standard_price',
            field=models.IntegerField(blank=True, help_text='정가', null=True),
        ),
    ]
