# Generated by Django 4.0.6 on 2022-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_standard_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='standard_price',
            field=models.IntegerField(blank=True, default=0, help_text='정가', null=True),
        ),
    ]
