# Generated by Django 4.1.1 on 2022-10-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=0, help_text='category 표시 순서 적을수록 위 순위', null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='index',
            field=models.IntegerField(default=0, help_text='subcategory 순서 적을수록 위 순위', null=True),
        ),
    ]
