# Generated by Django 4.1.1 on 2022-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_index_alter_subcategory_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=0, help_text='현재 제조 원가/공급가액'),
        ),
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='현재 재고 수준'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_soldout',
            field=models.IntegerField(default=0.0, help_text='재고 없음/품절'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.IntegerField(default=0, help_text='안전 재고 수준'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, help_text='총 판매 수량'),
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.ManyToManyField(to='product.category')),
                ('sub_categorys', models.ManyToManyField(to='product.subcategory')),
            ],
        ),
    ]
