# Generated by Django 4.1.1 on 2022-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_cost_product_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_soldout',
            field=models.IntegerField(default=0.0, help_text='재고 없음'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_seil_percent',
            field=models.CharField(blank=True, help_text='세일 %', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_seil_prace',
            field=models.CharField(blank=True, help_text='세일 가격', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.IntegerField(blank=True, help_text='현재 판매가', null=True),
        ),
    ]
