# Generated by Django 4.1.1 on 2022-10-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_is_soldout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
