# Generated by Django 4.1.1 on 2022-10-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_feed_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
            ],
        ),
    ]
