# Generated by Django 4.1.1 on 2022-10-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_feed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_manual',
            field=models.TextField(blank=True, help_text='상품 설명서'),
        ),
    ]
