# Generated by Django 4.1.1 on 2022-10-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_click_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_click',
            name='cat_id',
        ),
    ]
