# Generated by Django 4.1.1 on 2022-10-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_product_click_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_click',
            name='cat_id',
            field=models.IntegerField(default=0),
        ),
    ]
