# Generated by Django 4.1.1 on 2022-10-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_delete_product_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_check', models.BooleanField()),
                ('product_img', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_amount', models.IntegerField()),
            ],
        ),
    ]
