# Generated by Django 4.1.1 on 2022-10-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='is_check',
            field=models.BooleanField(default=True),
        ),
    ]
