# Generated by Django 4.1.1 on 2022-10-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_shoppingcart_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='sum_price',
            field=models.IntegerField(default=0),
        ),
    ]
