# Generated by Django 4.1.1 on 2022-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_shoppingcart_sum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='sum_price',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
