# Generated by Django 4.1.1 on 2022-11-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_shoppingcart_sum_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='categorys',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='sub_categorys',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ShopProduct',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
