# Generated by Django 4.1.1 on 2022-11-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_shoppingcart_remove_shopproduct_categorys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(blank=True, default=0, help_text='현재 제조 원가/공급가액', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(blank=True, default=0, help_text='현재 재고 수준', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_soldout',
            field=models.IntegerField(blank=True, default=0, help_text='재고 없음', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_manual',
            field=models.TextField(blank=True, help_text='상품 설명서', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_stock',
            field=models.IntegerField(blank=True, default=0, help_text='안전 재고 수준', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(blank=True, default=0, help_text='총 판매 수량', null=True),
        ),
    ]
