# Generated by Django 4.0.6 on 2022-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product_cost_alter_product_current_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
