# Generated by Django 4.0.6 on 2022-11-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_product_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_time',
        ),
    ]
