# Generated by Django 4.0.6 on 2022-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_product_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
