# Generated by Django 4.1.1 on 2022-10-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_id_product_click'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_id',
            old_name='feed_id',
            new_name='cat_id',
        ),
    ]
