# Generated by Django 4.1.1 on 2022-10-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_feed_id_category_id_cat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_click',
        ),
    ]
