# Generated by Django 4.1.1 on 2022-11-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_search_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='category name', max_length=32)),
                ('index', models.IntegerField(default=0, help_text='category 표시 순서 적을수록 위 순위', null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.ManyToManyField(to='main.category')),
            ],
            options={
                'db_table': 'ShopProduct',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='subcategory name', max_length=32)),
                ('index', models.IntegerField(default=0, help_text='subcategory 순서 적을수록 위 순위', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'db_table': 'SubCategory',
            },
        ),
        migrations.DeleteModel(
            name='Photo_advertisement',
        ),
        migrations.DeleteModel(
            name='Search_pro',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='sub_categorys',
            field=models.ManyToManyField(to='main.subcategory'),
        ),
    ]
