# Generated by Django 4.1 on 2022-09-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
