# Generated by Django 4.1 on 2022-09-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_userm_remove_user_address_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
