# Generated by Django 4.0.6 on 2022-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
