# Generated by Django 4.0.6 on 2022-09-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id_user',
        ),
    ]
