# Generated by Django 4.0.6 on 2022-09-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_rename_user_id_user_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_user',
            new_name='nickname',
        ),
    ]
