# Generated by Django 4.0.6 on 2022-09-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_rename_id_user_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
